myapp/urls.py
from django.urls import path
from . import views
app_name = 'myapp'
urlpatterns = [
    path('', views.welcome, name='home'),
    path('load_form', views.load_form, name='load_form'),
    path('add', views.add, name='add'),
    path('show', views.show, name='showall'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('showproject', views.showproject, name='showproject'),
    path('addproject', views.addproject, name='addproject'),
    path('addpr', views.addprd, name='addprs'),
]

myproject/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from myapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),

]

myapp/models.py
from django.db import models
from numpy import unique

# Create your models here.


class Project(models.Model):
    projectname = models.CharField(max_length=50, default='', unique=True)

    def __str__(self):
        return self.projectname


class Employee(models.Model):
    projectid = models.ForeignKey(Project, on_delete=models.CASCADE)
    eid = models.CharField(max_length=50)
    ename = models.CharField(max_length=50)
    email = models.EmailField()
    econtact = models.CharField(max_length=50)

    def __str__(self):
        return self.ename

myapp/forms.py
from django import forms
from .models import Employee, Project


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'


class Projectform(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'

myapp/views.py
from email import message
from django.shortcuts import render, redirect
from .models import Employee, Project
from .forms import EmployeeForm, Projectform
from django.contrib import messages
# Create your views here.


def welcome(request):
    te = Employee.objects.all().count()
    tp = Project.objects.all().count()
    return render(request, "welcome.html", {'te': te, 'tp': tp})


def addproject(request):
    form = Projectform
    return render(request, 'project.html', {'pr': form})


def addprd(request):
    ft = Projectform(request.POST)
    if ft.is_valid():

        ft.save()
        return redirect('/showproject')
    else:
        # for i in ft:
        # if i.errors:
        #     print(i.name)
        return render(request, 'error.html', {'context': ft})


def load_form(request):
    form = EmployeeForm
    return render(request, "index.html", {'form': form})


def add(request):
    form = EmployeeForm(request.POST)
    form.save()
    return redirect('/show')


def show(request):
    employee = Employee.objects.all().order_by('id')
    return render(request, "show.html", {'employee': employee})


def edit(request, id):
    employee = Employee.objects.get(id=id)
    prm = Project.objects.all().order_by('id')
    return render(request, 'edit.html', {'employee': employee, 'prm': prm})


def update(request, id):
    employee = Employee.objects.get(id=id)

    form = EmployeeForm(request.POST, instance=employee)

    # for field in form:
    # print("Field Error:", field.name,  field.errors)
    form.save()
    return redirect('/show')
    # return redirect('/show')


def delete(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect('/show')


def showproject(request):
    project = Project.objects.all().order_by('id')

    if request.method == 'GET':
        context = {'project': project}
    else:
        employee = Employee.objects.filter(projectid=request.POST['pid'])
        context = {'Employee': employee, 'project': project}

    return render(request, "showproject.html", context)

myapp/templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=., initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>





    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid ">
            <a class="navbar-brand" href="#">STUDENT ATTENDANCE SYSTEM</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item ">
                        <a class="nav-link active" aria-current="page" href="{% url 'myapp:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:load_form' %}">Add</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:showall' %}">Show</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:addproject' %}">Add Project</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:showproject' %}">Projects</a>
                    </li>
                    
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-dark btn-light" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="text-light container text-center mt-5 bg-primary">
        <h2 class="  shadow-lg p-3 mb-3 rounded">EDIT STUDENT</h2>
    </div>
    <div class="container p-4 text-center mt-2 border border-primary">

        <form class="d-flex justify-content-center mt-3" method="POST" action="/update/{{ employee.id }}">
            {% csrf_token %}

            <table class="mt-3 ">

                <tr>
                    <td>
                        <select name="projectid" id="">
                            {% for i in prm %}
                            <option value="{{ i.id }}">
                                {{i.projectname}}

                            </option>
                            {% endfor %}
                        </select>
                        <!-- <input name="projectid" required value={{ employee.projectid }}> -->
                    </td>
                </tr>

                <tr>
                    <td><input name="eid" required value="{{ employee.eid }}"></td>
                </tr>

                <tr>
                    <td><input name="ename" required value="{{ employee.ename }}"></td>
                </tr>

                <tr>
                    <td><input type="email" name="email" required value="{{ employee.email }}"></td>
                </tr>

                <tr>
                    <td><input name="econtact" required value="{{ employee.econtact }}"></td>
                </tr>

                <tr>
                    <td class="d-grid gap-2">
                        <button class="mt-3 btn btn-primary" type="submit">Update</button>
                    </td>
                </tr>
            </table>

        </form>
        <div>{{ mess }}</div>
    </div>

</body>

</html>

myapp/templates/error.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>

</body>

</html>






<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid ">
        <a class="navbar-brand" href="#">STUDENT ATTENDANCE SYSTEM</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item ">
                    <a class="nav-link active" aria-current="page" href="{% url 'myapp:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:load_form' %}">Add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:showall' %}">Show</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:addproject' %}">Add Project</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:showproject' %}">Projects</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-dark btn-light" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

<div class=" text-dark p-4 container rounded-left text-center border-2  mt-3 ">

    <h2 class=" text-light bg-primary shadow-lg p-3 mb-3 rounded">ADD PROJECT</h2>
    <h5 class="font-weight-bold"> PROJECT {{context.projectname}} ALREADY ADDED </h5>
    <a class="btn btn-primary" href="{% url 'myapp:addproject' %}">Add New Project</a>
</div>



</body>

</html>

myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Document</title>
</head>

<body>

</body>

</html>






<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid ">
    <a class="navbar-brand" href="#">STUDENT ATTENDANCE SYSTEM</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
      aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item ">
          <a class="nav-link active" aria-current="page" href="{% url 'myapp:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:load_form' %}">Add</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:showall' %}">Show</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:addproject' %}">Add Project</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:showproject' %}">Projects</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark btn-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div class=" text-dark p-4 container rounded-left text-center border-2  mt-3 ">

  <h2 class=" text-light bg-primary shadow-lg p-3 mb-3 rounded">ADD STUDENT</h2>
  <form class="p-3 border border-primary" method="POST" action="add">
    {% csrf_token %}
    <h5>STUDENT ID</h5>
    <div>{{ form.eid }}</div>

    <h5 class="mt-2">STUDENT NAME</h5>
    <div>{{ form.ename }}</div>

    <h5 class="mt-2">EMAIL</h5>
    <div>{{ form.email }}</div>

    <h5 class="mt-2">STUDENT CONTACT</h5>
    <div>{{ form.econtact }}</div>

    <h5 class="mt-2">ASSIGN PROJECT</h5>
    <div>{{ form.projectid }}</div>
    <br>
    <div><button class="btn btn-primary" type="Submit">ADD</button></div>
  </form>
</div>

myapp/templates/project.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>

</body>

</html>






<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid ">
        <a class="navbar-brand" href="#">STUDENT ATTENDANCE SYSTEM</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item ">
                    <a class="nav-link active" aria-current="page" href="{% url 'myapp:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:load_form' %}">Add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:showall' %}">Show</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:addproject' %}">Add Project</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:showproject' %}">Projects</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-dark btn-light" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

<div class=" text-dark p-4 container rounded-left text-center border-2  mt-3 ">

    <h2 class=" text-light bg-primary shadow-lg p-3 mb-3 rounded">ADD PROJECT</h2>
    <form class="p-3 border border-primary" method="POST" action="{% url 'myapp:addprs' %}">
        {% csrf_token %}
        <!-- <div>{{pr}} </div> -->
        <h5>Project Name</h5>

        <div>{{ pr.projectname }}</div>



        <div><button class="btn btn-primary mt-2 btn-md" type="Submit">ADD</button></div>
    </form>



    </body>

    </html>

myapp/templates/show.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid ">
            <a class="navbar-brand" href="#">STUDENT ATTENDANCE SYSTEM</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item ">
                        <a class="nav-link active" aria-current="page" href="{% url 'myapp:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:load_form' %}">Add</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:showall' %}">Show</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:addproject' %}">Add Project</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:showproject' %}">Projects</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-dark btn-light" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container text-center mt-5">
        <h2 class=" text-light bg-primary shadow-lg p-3 mb-3 rounded">ALL STUDENTS</h2>
        <table class="border-dark border table table-striped">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Project Name</th>
                <th>Action</th>
                <th>Action</th>
            </tr>

            {% for i in employee %}
            <tr>
                <td>{{ i.eid }}</td>
                <td>{{ i.ename }}</td>
                <td>{{ i.email }}</td>
                <td>{{ i.econtact }}</td>
                <td>{{ i.projectid }}</td>
                <td>
                    <a class="btn btn-primary" href="edit/{{ i.id }}">Edit</a>
                </td>
                <td>
                    <a class="btn btn-primary" href="delete/{{ i.id }}">Delete</a>
                </td>
            </tr>
            {% endfor %}



        </table>
        
    </div>

</body>

</html>

myapp/templates/showproject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid ">
        <a class="navbar-brand" href="#">STUDENT ATTENDANCE SYSTEM</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item ">
                    <a class="nav-link active" aria-current="page" href="{% url 'myapp:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:load_form' %}">Add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:showall' %}">Show</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:addproject' %}">Add Project</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:showproject' %}">Projects</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-dark btn-light" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

<div class=" text-dark container rounded-left text-center border-2  mt-3 ">

    <h2 class=" text-light bg-primary shadow-lg p-3 mb-3 rounded">PROJECTS</h2>
<form class="" method="POST" action="">

    {% csrf_token %}
<select class="form-select form-select-md mb-3" aria-label=".form-select-lg example" name="pid">
    
    {% for i in project  %}
        <option value={{ i.id }}>
            {{ i.projectname }}
        </option>
    {% endfor %}

</select>


<input class="btn btn-primary" type="submit" value="search">
</form>
<div>
{% if Employee %}
<table class="border-dark border mt-5 table table-striped" >
    <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Contact</th>
        <th>Project Name</th>
        
    </tr>

    {% for i in Employee %}
    <tr>
        <td>{{ i.eid }}</td>
        <td>{{ i.ename }}</td>
        <td>{{ i.email }}</td>
        <td>{{ i.econtact }}</td>
        <td>{{ i.projectid }}</td>
        
    </tr>
    {% endfor %}

{% endif %}

</table>
</body>
</html>

myapp/templates/welcome.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Document</title>
</head>

<body>



  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid ">
      <a class="navbar-brand" href="#">STUDENT ATTENDANCE SYSTEM</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
        aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item ">
            <a class="nav-link active" aria-current="page" href="{% url 'myapp:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:load_form' %}">Add</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:showall' %}">Show</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:addproject' %}">Add Project</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:showproject' %}">Projects</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-dark btn-light" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>




  <div class="container mt-5 text-center">
    <h2 class=" text-light bg-primary shadow-lg p-3 mb-3 rounded">STUDENT ATTENDANCE SYSTEM</h2>
    <div class="row shadow-lg p-3 mb-3  rounded">

      <div class="card">
        <div class=" card-body">
          <div class="row">
            <div class="col-md-3">
              <a class="text-decoration-none text-light" href="{% url 'myapp:load_form' %}">
                <div class="card bg-primary my-card shadow text-center p-3">
                  <h4>ADD STUDENTS </h4>
                  <div><svg xmlns="http://www.w3.org/2000/svg" width="30" height="42" fill="currentColor"
                      class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                      <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                      <path fill-rule="evenodd"
                        d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
                    </svg></div>
                </div>

              </a>
            </div>
            <div class="col-md-3">
              <a class="text-decoration-none text-light" href="{% url 'myapp:addproject' %}">
                <div class="card bg-primary my-card shadow text-center p-3">
                  <h4>ADD PROJECTS </h4>
                  <div><svg xmlns="http://www.w3.org/2000/svg" width="30" height="42" fill="currentColor"
                      class="bi bi-clipboard-data-fill" viewBox="0 0 16 16">
                      <path
                        d="M6.5 0A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3Zm3 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3Z" />
                      <path
                        d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1A2.5 2.5 0 0 1 9.5 5h-3A2.5 2.5 0 0 1 4 2.5v-1ZM10 8a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0V8Zm-6 4a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0v-1Zm4-3a1 1 0 0 1 1 1v3a1 1 0 1 1-2 0v-3a1 1 0 0 1 1-1Z" />
                    </svg></div>
                </div>

              </a>
            </div>
            <div class="col-md-3">
              <a class="text-decoration-none text-light " href="{% url 'myapp:showall' %}">
                <div class="card bg-primary my-card shadow text-center p-3 ">
                  <h4>ALL STUDENTS <i class="fas fa-box"></i></h4>
                  <h3>{{te}}</h3>
                </div>
              </a>
            </div>

            <div class="col-md-3">
              <a class="text-decoration-none text-light" href="{% url 'myapp:showproject' %}">
                <div class="card bg-primary my-card shadow text-center p-3">
                  <h4>PROJECTS<i class="fas fa-shipping-fast"></i></h4>
                  <h3>{{tp}}</h3>
                </div>
            </div>
          </div>

        </div>
        <!-- <div class="col-lg-4">
          <a href="{% url 'myapp:load_form' %}" class="btn btn-primary btn-lg ">
            ADD STUDENT
          </a>

        </div>
        <div class="col-lg-4">
          <a href="{% url 'myapp:showall' %}" class="btn btn-primary btn-lg ">
            ALL STUDENTS
          </a>

        </div>
        <div class="col-lg-4">

          <a href="{% url 'myapp:showproject' %}" class="btn btn-primary btn-lg ">
            PROJECTS
          </a>
        </div> -->

      </div>

    </div>
  </div>

</body>

</html>